# Generated by Django 5.1.7 on 2025-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0002_alter_financialindex_id_alter_infoproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproduct',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='category',
            field=models.CharField(choices=[('0', 'Poisson'), ('1', 'Coquillage'), ('2', 'Crustacé')], max_length=200),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='comments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='owner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='quantityInStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infoproduct',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ChiffreAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('statut', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('JOURNALIER', 'Journalier'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], max_length=20)),
                ('totalAvecSolde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalSansSolde', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transactions', models.ManyToManyField(to='monTiGMagasin.transaction')),
            ],
            options={
                'ordering': ['-date', '-type'],
            },
        ),
    ]
