# Generated by Django 5.1.7 on 2025-03-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monMag', '0003_produitenpromotion_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitenpromotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
