# Generated by Django 5.1.7 on 2025-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monMag', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProduitEnPromo',
            new_name='ProduitEnPromotion',
        ),
    ]
