# Generated by Django 5.1.7 on 2025-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monMag', '0002_rename_produitenpromo_produitenpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitenpromotion',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
